require("prototypes.recipe-updates")
require("prototypes.entity-updates")
require("prototypes.technology-updates")
require("prototypes.tips-and-tricks-updates")
require("prototypes.planet.planet-updates")
require("prototypes.item-updates")